### ISSUE TITLE
Move error handler to error mapper

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl-go#1]
Make `sysl-go-comms` responsible for handling (i.e. writing) errors, not just reporting them to custom code. 

In the current interaction pattern, `sysl-go-comms` requests that custom code handle errors. This requires that custom code map an error to an `HTTPError`, then write the `HTTPError` out:

```go
func HandleError(ctx context.Context, w http.ResponseWriter, kind common.Kind, message string, cause error) {
    // map error to http error
    // write http error
}
```

The replacement interaction pattern moves the responsibility of writing the `HTTPError` into `sysl-go-comms` and keeping custom code responsible for mapping the error: 

```go
func MapError(ctx context.Context, kind common.Kind, message string, cause error) common.HTTPError {
    // return mapped http error
}
```

**Comment by gkanz** [comment]
May need to expand on this one a bit.

**Comment by tiagralee** [comment]
Hi guys, I had a bit look at this, below is a current test interaction looks like:

```
func (c Callback) HandleError(ctx context.Context, w http.ResponseWriter, kind common.Kind, message string, cause error) {
	se := common.CreateError(ctx, kind, message, cause)

	httpError := common.HandleError(ctx, se)

	httpError.WriteError(ctx, w)
}

```

Does the change will look like below?


```
func (c Callback) HandleError(ctx context.Context, w http.ResponseWriter, kind common.Kind, message string, cause error) common.HttpError {
        return common. MapError(ctx, kind, message, cause)
}
```

Not quit clear where the write http error will go.

**Comment by gkanz** [comment]
Just getting some time this morning to think about this more deeply... apologies. 

Desired outcome: custom code needs to do as little as possible to map internal errors to external errors.

The current behaviour is:
1. Either the custom code or the Sysl library returns an error.
1. **HTTP handler** calls a custom-written **Callback** function to map the error to an HTTP error.
1. **Callback** maps its own errors then calls the Sysl library so that it can map errors it knows about.
1. **Callback** function then uses the passed in writer to write the error.

The suggested behaviour for programmatic mapping is:
1. Either the custom code or the Sysl library returns an error.
1. **HTTP handler** calls a custom mapper callback.
1. **Callback** uses [errors.As](https://golang.org/pkg/errors/#As) to see if it wants to  map any errors and returns a HTTPError if it does. If it doesn't then it returns nil.
1. **HTTP handler** either recieves a mapped error or nil from **Callback**. If it recevies the mapped error, it writes the error, if it receives nil it calls `sysl-go` to get a mapping. 
1. `sysl-go` uses config to map errors and MUST return a mapping if there is an error.
1. **HTTP handler** writes the error from `sysl-go`.

The suggested behaviour for static mapping is:
1. Either the custom code or the Sysl library returns an error.
1. **HTTP handler** calls a generated mapper function that uses config to map errors. The error types are generated from Sysl. If none of the generated types are mapped in the config then the generated function will just return nil. **HTTP handler** then calls the `sysl-go` mapper that maps internal error types.
1. **HTTP handler** writes the error.

The programmatic approach gives the developer more flexibility in how return codes are selected but is more work on their part, static mapping is more restrictive: this type of internal error == that type of external error.

Approach:
- The error codes should be in configuration which can be filled in with default values when the project is initially set up and updated later.
- Use Go 13 error handling: https://blog.golang.org/go1.13-errors, and see usage and extensions written by @camh-anz and @juliaogris here: https://github.com/anzx/vcards/tree/master-vendored/internal/errs.
- No reflection should be necessary.
- If we choose static mapping then there is no point using types, we should just use error sentinels (see Cam and Julia's work) and use [errors.Is](https://golang.org/pkg/errors/#Is) instead of `errors.As`. Error types are only needed if you want to cast them and use the internal structured information to make more complex decisions.

### Static Mapping
There is no callback, Sysl needs to generate a function like:
```go
func MapError(ctx context.Context, err error) *common.HTTPError {
    // use errors.As to detect type and look up config
    // return mapped http error if mapping found else return nil
}
```

There is no agreed way to specify error types used internally by custom code, just external ones:
```
App:
    /endpoint:
        GET:
            return error <: ErrorType
```

I think error types belong to the application, so something like this might work:
```
App:
    @errorTypes = ["ErrorType1", "ErrorType2"]
```
with matching configuration
```
ErrorMapping
  ErrorType1
    Code
    Message
```
