### ISSUE TITLE
go get github.com/anz-bank/sysl-go doesn't work

### ISSUE THREAD

**Issue by orlade** [anz-bank/sysl-go#191]
The README says to run `go get github.com/anz-bank/sysl-go` but it fails:

```
$ go get github.com/anz-bank/sysl-go
can't load package: package github.com/anz-bank/sysl-go: no Go files in /home/orlade/.gvm/pkgsets/go1.14/global/src/github.com/anz-bank/sysl-go
```

**Comment by orlade** [comment]
I think it needs `GO111MODULE=on` in front.

**Comment by joshcarp** [comment]
since go 1.13 GO111MODULE=on is set by default if you're in a go module (a project with a go.mod file).
The only reason why you'd want to run `go get` outside of a go module these days would be to install a binary,  but this repo is only made up of packages and no installable binaries, so that wouldn't really ever be the case
see the go changelog here: https://golang.org/doc/go1.13#tools
